
// This file has been generated by the GUI designer. Do not modify.
namespace cn.qingyuyu.yudesk.view
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action SettingAction;

		private global::Gtk.Action TokenAction;

		private global::Gtk.Action AboutAction;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.MenuBar menubar;

		private global::Gtk.Label infoLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget cn.qingyuyu.yudesk.view.MainWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.SettingAction = new global::Gtk.Action("SettingAction", global::Mono.Unix.Catalog.GetString("Setting"), null, null);
			this.SettingAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Setting");
			w1.Add(this.SettingAction, null);
			this.TokenAction = new global::Gtk.Action("TokenAction", global::Mono.Unix.Catalog.GetString("Token"), null, null);
			this.TokenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Token");
			w1.Add(this.TokenAction, null);
			this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
			this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
			w1.Add(this.AboutAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "cn.qingyuyu.yudesk.view.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child cn.qingyuyu.yudesk.view.MainWindow.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar\'><menu name=\'SettingAction\' action=\'SettingAction\'><me" +
					"nuitem name=\'TokenAction\' action=\'TokenAction\'/><menuitem name=\'AboutAction\' act" +
					"ion=\'AboutAction\'/></menu></menubar></ui>");
			this.menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar")));
			this.menubar.Name = "menubar";
			this.fixed2.Add(this.menubar);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.menubar]));
			w2.X = 4;
			w2.Y = 4;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.infoLabel = new global::Gtk.Label();
			this.infoLabel.Name = "infoLabel";
			this.infoLabel.LabelProp = global::Mono.Unix.Catalog.GetString("label3");
			this.fixed2.Add(this.infoLabel);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.infoLabel]));
			w3.X = 80;
			w3.Y = 70;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 255;
			this.DefaultHeight = 165;
			this.Show();
			this.TokenAction.Activated += new global::System.EventHandler(this.OnTokenActionActivated);
			this.AboutAction.Activated += new global::System.EventHandler(this.OnAboutActionActivated);
		}
	}
}
