
// This file has been generated by the GUI designer. Do not modify.
namespace cn.qingyuyu.yudesk.view
{
	public partial class InputDialog
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Label infoLabel;

		private global::Gtk.Entry textEdit;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget cn.qingyuyu.yudesk.view.InputDialog
			this.Name = "cn.qingyuyu.yudesk.view.InputDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child cn.qingyuyu.yudesk.view.InputDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.infoLabel = new global::Gtk.Label();
			this.infoLabel.Name = "infoLabel";
			this.infoLabel.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.fixed3.Add(this.infoLabel);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.infoLabel]));
			w2.X = 12;
			w2.Y = 20;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.textEdit = new global::Gtk.Entry();
			this.textEdit.CanFocus = true;
			this.textEdit.Name = "textEdit";
			this.textEdit.Text = global::Mono.Unix.Catalog.GetString("11111");
			this.textEdit.IsEditable = true;
			this.textEdit.InvisibleChar = '•';
			this.fixed3.Add(this.textEdit);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.textEdit]));
			w3.X = 58;
			w3.Y = 59;
			w1.Add(this.fixed3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1[this.fixed3]));
			w4.Position = 0;
			// Internal child cn.qingyuyu.yudesk.view.InputDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5[this.buttonCancel]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5[this.buttonOk]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 259;
			this.DefaultHeight = 159;
			this.Show();
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
